export type ToolCategory = "ai" | "app" | "data" | "infra";

export interface Tool {
  name: string;
  category: ToolCategory;
}

export const TOOLS: Tool[] = [
  // AI & Machine Learning
  { name: "Claude (text + vision)", category: "ai" },
  { name: "GPT (text + vision)", category: "ai" },
  { name: "Gemini (multimodal)", category: "ai" },
  { name: "Realtime audio models", category: "ai" },
  { name: "Image generation", category: "ai" },
  { name: "Video generation", category: "ai" },
  { name: "Open-weight LLMs", category: "ai" },
  { name: "OpenRouter", category: "ai" },
  { name: "LangGraph", category: "ai" },
  { name: "LlamaIndex", category: "ai" },
  { name: "Pydantic AI", category: "ai" },
  { name: "Structured output pipelines", category: "ai" },
  { name: "Prompt engineering", category: "ai" },
  { name: "PyTorch", category: "ai" },
  { name: "Hugging Face", category: "ai" },
  { name: "Transformers", category: "ai" },
  { name: "spaCy", category: "ai" },
  { name: "scikit-learn", category: "ai" },
  { name: "vLLM", category: "ai" },
  { name: "NumPy", category: "ai" },
  { name: "pandas", category: "ai" },
  { name: "matplotlib", category: "ai" },
  { name: "seaborn", category: "ai" },
  // Application Development
  { name: "Python", category: "app" },
  { name: "FastAPI", category: "app" },
  { name: "TypeScript", category: "app" },
  { name: "Next.js", category: "app" },
  { name: "React", category: "app" },
  { name: "Remix", category: "app" },
  { name: "SvelteKit", category: "app" },
  { name: "Tailwind", category: "app" },
  { name: "Framer Motion", category: "app" },
  { name: "REST APIs", category: "app" },
  { name: "Microservices", category: "app" },
  { name: "Firebase (Auth, Firestore, Realtime)", category: "app" },
  // Data & Storage
  { name: "Postgres", category: "data" },
  { name: "SQL Server", category: "data" },
  { name: "SQLite", category: "data" },
  { name: "Snowflake", category: "data" },
  { name: "BigQuery", category: "data" },
  { name: "Databricks", category: "data" },
  { name: "DuckDB", category: "data" },
  { name: "Supabase", category: "data" },
  { name: "pgvector", category: "data" },
  { name: "Pinecone", category: "data" },
  { name: "MongoDB", category: "data" },
  { name: "DynamoDB", category: "data" },
  { name: "Redis", category: "data" },
  { name: "Elasticsearch", category: "data" },
  { name: "ETL pipelines", category: "data" },
  { name: "Unstructured data (PDFs, docs, audio, images)", category: "data" },
  { name: "Geospatial data", category: "data" },
  { name: "Computer vision pipelines", category: "data" },
  { name: "Multi-modal media assembly", category: "data" },
  // Infrastructure & Observability
  { name: "AWS", category: "infra" },
  { name: "GCP", category: "infra" },
  { name: "Azure", category: "infra" },
  { name: "Vercel", category: "infra" },
  { name: "Render", category: "infra" },
  { name: "Fly.io", category: "infra" },
  { name: "Railway", category: "infra" },
  { name: "Kubernetes", category: "infra" },
  { name: "Docker", category: "infra" },
  { name: "Terraform", category: "infra" },
  { name: "Helicone", category: "infra" },
  { name: "Langfuse", category: "infra" },
  { name: "Sentry", category: "infra" },
  { name: "Grafana", category: "infra" },
  { name: "PostHog", category: "infra" },
  { name: "Google Analytics", category: "infra" },
  { name: "Umami", category: "infra" },
  { name: "Metabase", category: "infra" },
];

export const TOOL_CATEGORIES = [
  { id: "ai" as const, label: "AI & Machine Learning", desig: "A" },
  { id: "app" as const, label: "Application Development", desig: "D" },
  { id: "data" as const, label: "Data & Storage", desig: "S" },
  { id: "infra" as const, label: "Infrastructure & Observability", desig: "I" },
];

export const TOOL_FILTERS = [
  { key: "all", label: "All" },
  { key: "ai", label: "AI / ML" },
  { key: "app", label: "App Dev" },
  { key: "data", label: "Data" },
  { key: "infra", label: "Infra / Obs" },
] as const;
